# Generated by Django 4.1.3 on 2022-11-25 16:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('birthday_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
