# Generated by Django 4.1.3 on 2022-11-30 03:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_name_alter_contact_note_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('birthdays', django.db.models.manager.Manager()),
            ],
        ),
    ]
