# Generated by Django 4.1.3 on 2022-12-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='web',
            field=models.URLField(blank=True, default='https://', max_length=300, null=True),
        ),
    ]
