# Generated by Django 4.1.3 on 2022-12-03 02:35

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
    ]
